version: "3.9"
services:
  server:
    build: ./server
    ports:
    - "5000:5000"
    volumes:
    - ./server:/app
    environment:
      FLASK_ENV: development
  client:
    build: ./client
    ports:
    - "3000:3000"
    volumes:
      - ./client:/user/src/app
      - /user/src/app/node_modules
    depends_on:
      - server



